# Generated by Django 3.2.20 on 2023-09-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile233',
            new_name='UserProfile',
        ),
    ]
