# Generated by Django 3.2.20 on 2023-09-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_nums',
            field=models.IntegerField(default=3),
        ),
    ]
