# Generated by Django 3.2.20 on 2023-09-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_card_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
