# Generated by Django 3.2.20 on 2023-09-02 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_image_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('id_card_front_url', models.URLField()),
                ('id_card_back_url', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('video_list', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('company_images', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
