# Generated by Django 3.2.20 on 2023-09-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230902_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(default='abcdefghijkl', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
