# Generated by Django 3.2.20 on 2023-09-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230903_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cards', to='myapp.company'),
        ),
    ]
