# Generated by Django 3.2.20 on 2023-09-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_card_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_code',
            field=models.CharField(max_length=12),
        ),
    ]
