# Generated by Django 3.2.20 on 2023-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_card_card_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bossname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='credit_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='license_image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
