# Generated by Django 3.2.20 on 2023-09-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20230904_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_back_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_front_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
